version: 0.2

env:
  shell: bash
  secrets-manager:
    IO_SERVER_URL: IO_INTEGRATION:IO_SERVER_URL
    IO_ACCESS_TOKEN: IO_INTEGRATION:IO_ACCESS_TOKEN
    WORKFLOW_ENGINE_SERVER_URL: IO_INTEGRATION:WORKFLOW_ENGINE_SERVER_URL
    POLARIS_SERVER_URL: IO_INTEGRATION:POLARIS_SERVER_URL
    POLARIS_ACCESS_TOKEN: IO_INTEGRATION:POLARIS_ACCESS_TOKEN
  variables:
     IS_SAST_ENABLED: false
     IS_SCA_ENABLED: false
     IS_DAST_ENABLED: false
     SCM_TYPE: github
     GITHUB_WORKSPACE: devsecops-test
     GITHUB_REPO_NAME: github-io-sample
     GITHUB_BRANCH_NAME: master
     IO_ASSET_ID: "devsecops-test/aws-io-sample" 
     RELEASE_TYPE: major
     PERSONA: developer

phases:
  pre_build:
    commands:
      - echo ================Getting IO Actions================
      - wget https://intelligent-security-scan.s3.us-east-2.amazonaws.com/io_actions.sh
  build:
    commands:
      - echo ================Build Maven Package and Docker Image================
      - chmod +x io_actions.sh
      - sed -i -e 's/\r$//' io_actions.sh
      - ./io_actions.sh --stage=IO --workflow.version=2021.04 --manifest.type=json
      - source io_actions.meta.env
      - echo "Is SAST Enabled=${IS_SAST_ENABLED}"
      - echo "Is SCA Enabled=${IS_SCA_ENABLED}"
      #Update Prescription Results to Parameter Store
      - aws ssm put-parameter --name "IO_IS_SAST_ENABLED" --value ${IS_SAST_ENABLED} --type "String" --region "us-east-2" --overwrite
      - aws ssm put-parameter --name "IO_IS_SCA_ENABLED" --value ${IS_SCA_ENABLED} --type "String" --region "us-east-2" --overwrite
