version: 0.2

env:
  parameter-store:
     sast_enable: "IO_IS_SAST_ENABLED"
phases:
  build:
    commands:
      - echo WorklowEngine
      - IS_SAST_ENABLED=$(aws ssm get-parameters --region us-east-2 --names IO_IS_SAST_ENABLED --query Parameters[0].Value)
      - echo $IS_SAST_ENABLED
      - IS_SCA_ENABLED=$(aws ssm get-parameters --region us-east-2 --names IO_IS_SCA_ENABLED --query Parameters[0].Value)
      - echo $IS_SCA_ENABLED
      - echo $sast_enable
